# Generated by Django 4.2.3 on 2023-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_detection_project', '0003_randomnumber_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
